package qtrade

type Currency string

const (
	USDT  Currency = "USDT"
	BAN   Currency = "BAN"
	BTM   Currency = "BTM"
	DOGE  Currency = "DOGE"
	MCM   Currency = "MCM"
	WEBD  Currency = "WEBD"
	QUAN  Currency = "QUAN"
	PEG   Currency = "PEG"
	RVN   Currency = "RVN"
	BAC   Currency = "BAC"
	CCX   Currency = "CCX"
	XEQ   Currency = "XEQ"
	RUPX  Currency = "RUPX"
	PHL   Currency = "PHL"
	FCT   Currency = "FCT"
	DGB   Currency = "DGB"
	XBR   Currency = "XBR"
	ETH   Currency = "ETH"
	BTC   Currency = "BTC"
	SCC   Currency = "SCC"
	PUSD  Currency = "pUSD"
	REDN  Currency = "REDN"
	SNOW  Currency = "SNOW"
	HTR   Currency = "HTR"
	CPR   Currency = "CPR"
	CRUZ  Currency = "CRUZ"
	VEO   Currency = "VEO"
	KLP   Currency = "KLP"
	VLS   Currency = "VLS"
	NANO  Currency = "NANO"
	DEFT  Currency = "DEFT"
	LTC   Currency = "LTC"
	RCO   Currency = "RCO"
	TAO1  Currency = "TAO1"
	LUCK  Currency = "LUCK"
	WFCT  Currency = "WFCT"
	MMO   Currency = "MMO"
	NYZO  Currency = "NYZO"
	BWS20 Currency = "BWS20"
	BWS10 Currency = "BWS10"
	THC   Currency = "THC"
	XTO   Currency = "XTO"
	GRIN  Currency = "GRIN"
	PASC  Currency = "PASC"
	ARMS  Currency = "ARMS"
	RTM   Currency = "RTM"
	ZANO  Currency = "ZANO"
	ANU   Currency = "ANU"
	XCP   Currency = "XCP"
	ARO   Currency = "ARO"
	BIS   Currency = "BIS"
	IDNA  Currency = "IDNA"
	HLS   Currency = "HLS"
	PFCT  Currency = "pFCT"
)

type CurrencyStatus string

const (
	CurrencyStatusOK       CurrencyStatus = "ok"
	CurrencyStatusDegraded CurrencyStatus = "degraded"
	CurrencyStatusDisabled CurrencyStatus = "disabled"
	CurrencyStatusOffline  CurrencyStatus = "offline"
	CurrencyStatusDelisted CurrencyStatus = "delisted"
)
